riotwatcher/__init__.py
Seems like using from riotwatcher import * in the init was only importing the riotwatcher project directory. This fixes it by using a relative path.
=> Fixes issue #19 with importing classes in Python3.4.

README.rst
As required by Riot, there needs to be [a specifically-worded attribution statement](https://developer.riotgames.com/terms#statement), otherwise you risk them revoking your license to use the Riot API.
=> Attribution needs to comply to the TOS

riotwatcher/riotwatcher.py
Per documentation at https://developer.riotgames.com/docs/rate-limiting, any 429 Response will contain headers that the user can use to help avoid Rate Limiting and blacklisting. All this change does is alter the LoLException object to have a headers property to allow a user of the library to utilize these returned headers.
=> Exposing response headers on LoLException object

riotwatcher/riotwatcher.py
While browsing the [rate-limiting docs](https://developer.riotgames.com/docs/rate-limiting) I noticed at the bottom there is a new(?) response code for if you manage to get your API key blacklisted; 403.
I don't have a blacklisted key to test this with, but it seems safe to assume this would work.
=> Add check for 403 response code.

riotwatcher/riotwatcher.py
These kwargs have incorrect ids which result in not being able to filter match lists by champion id or season.
=> Fix to get_match_list function

riotwatcher/riotwatcher.py
Applies to `ranked_queues`, `season`.
=> Coerce non-string iterables into strings for get_match_list args.

README.rst
While attempting to install the library in python3 by running
`python3 setup.py install`, the script crash while reading the Riot API
official licence (because of the copyright character). This fix simply
use the `(c)` instead of the copyright character.
=> Fixing encoding issue for Python3 installation

src/riotwatcher/_apis/DataDragonApi.py, tests/_apis/test_DataDragonApi.py
The current version of the DataDragon api doesn't have the runeReforged endpoint. This naively adds it.
Some version checking might be nice (so that runesReforged aren't requested on a version where they don't exist) but since these queries don't count against the rate limit and an error in such a case is returned anyway _caveat emptor_ is probably sufficient
=> Add runesReforged to DataDragon api

README.rst
also getting an error with `.e` here: `print('We should retry in {} seconds.'.format(e.headers['Retry-After']))`
=> minor updates to demo to comform to pep8, typo fixes

src/riotwatcher/Handlers/DeprecationHandler.py, src/riotwatcher/Handlers/RateLimit/HeaderBasedLimiter.py, src/riotwatcher/Handlers/RateLimit/Limits.py, src/riotwatcher/Handlers/RateLimit/OopsRateLimiter.py, src/riotwatcher/Handlers/RateLimit/RateLimitHandler.py, src/riotwatcher/Handlers/WaitingRateLimitHandler.py
While developing [a package](https://github.com/Steffo99/royalpack) that uses `riotwatcher`, I noticed that `riotwatcher` was logging to the `root` logger instead of the `riotwatcher` logger.
It is [a good practice](https://docs.python.org/3.8/library/logging.html#logger-objects) to log on the module logger `logging.getLogger(__name__)` instead of the root logger `logging.root`.
Having noticed that, I fixed it for you! 😄 
In every file that uses logging, I created a module logger with `log = logging.getLogger(__name__)`.
Then, I replaced all `logging.info(message)` calls with `log.info(message)` calls.
This way, packages that use `riotwatcher` can choose what to do with its logs (display only messages above a certain level, write them to a file, etc...).
=> Use the module logger instead of the root logger

src/riotwatcher/_apis/team_fight_tactics/LeagueApi.py, src/riotwatcher/_apis/team_fight_tactics/urls/LeagueApiUrls.py, tests/_apis/team_fight_tactics/test_LeagueApi.py, tests/integration/team_fight_tactics/test_LeagueApi.py
Add support for rated ladders of TFT league API by TFT season 5, but, Riot API currently only allows RANKED_TFT_TURBO on {queue} so a comment may need to be added.
=> add support new league api of TFT API

docs/riotwatcher/LeagueOfLegends/MatchApiV5.rst
docs header incorrectly states V4 instead of V5
=> fix typo in matchapiV5 docs header

src/riotwatcher/_apis/league_of_legends/DataDragonApi.py, src/riotwatcher/_apis/league_of_legends/urls/DataDragonUrls.py, tests/_apis/league_of_legends/test_DataDragonApi.py
This gets a list of all of the valid versions for Data Dragon. https://ddragon.leagueoflegends.com/api/versions.json
Pretty much just creates a `versions_all` method in `DataDragonApi` and the corresponding URL in `DataDragonUrls`. Also creates a test for the endpoint in `test_DataDragonApi`.
AFAIK this functionality wasn't previously implemented in Riot-Watcher.
=> Add Data Dragon versions endpoint. 

src/riotwatcher/_apis/league_of_legends/MatchApiV5.py
match id should be a string not a long in docs in v5
=> Fix documentation on match id

src/riotwatcher/_apis/helpers.py, tests/conftest.py
Since you finally decided to statically map regions and then riot changed them right after...
=> Change OCE to SEA Region

src/riotwatcher/_apis/team_fight_tactics/MatchApi.py, src/riotwatcher/_apis/team_fight_tactics/urls/MatchApiUrls.py, tests/_apis/team_fight_tactics/test_MatchApi.py, tests/integration/team_fight_tactics/test_MatchApi.py
I want to be able to get more that 100 TFT matches, as I'm sure many people do. This isn't possible without changing the start param, so I added it. I threw in some docs while I was at it.
=> Add support for start param in by_puuid function for MatchApi

src/riotwatcher/_apis/team_fight_tactics/MatchApi.py, tests/_apis/team_fight_tactics/test_MatchApi.py
These two parameters from Riot API were missing in the library.
=> fix: add missing startTime and endTime parameters to TFT MatchApi

docs/riotwatcher/LeagueOfLegends/SpectatorApiV5.rst, docs/riotwatcher/LeagueOfLegends/index.rst, src/riotwatcher/LolWatcher.py, src/riotwatcher/_apis/league_of_legends/SpectatorApiV5.py, src/riotwatcher/_apis/league_of_legends/__init__.py, src/riotwatcher/_apis/league_of_legends/urls/SpectatorApiUrls.py, src/riotwatcher/_apis/league_of_legends/urls/__init__.py, tests/_apis/league_of_legends/test_SpectatorApiV5.py, tests/integration/league_of_legends/test_SpectatorApiV5.py
Deprecate Spectator-V4 and add Spectator-V5
=> Add Spectator-V5

src/riotwatcher/_apis/league_of_legends/ChampionMasteryApiV4.py, src/riotwatcher/_apis/league_of_legends/urls/ChampionMasteryApiUrls.py, tests/_apis/league_of_legends/test_ChampionMasteryApiV4.py, tests/integration/league_of_legends/test_ChampionMasteryApiV4.py
=> Fully support new champion mastery endpoints

README.rst, docs/index.rst
Change documentation to reflect the removal of summoner names.
=> Update docs and README

README.rst, docs/index.rst, src/riotwatcher/_apis/league_of_legends/LeagueApiV4.py, src/riotwatcher/_apis/league_of_legends/urls/LeagueApiUrls.py, tests/_apis/league_of_legends/test_LeagueApiV4.py, tests/integration/league_of_legends/test_LeagueApiV4.py
- added the new endpoint
- added tests for that endpoint
- updated the example and README to use the new endpoint over the old one
=> Add the league-v4/entries/by-puuid endpoint
